//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramskoInzenjerstvo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BiljeNarudzba
    {
        public int IDBiljeNarudzba { get; set; }
        [RegularExpression("[^0-9]", ErrorMessage = "Samo brojevi")]
        [Required(ErrorMessage = "Kolicina je obavezno polje")]
        public int Kolicina { get; set; }
        [RegularExpression("[^0-9]", ErrorMessage = "Samo brojevi")]
        [Required(ErrorMessage = "Cijena je obavezno polje")]
        public decimal CijenaDogovoreno { get; set; }
        public Nullable<int> IDMjernaJedinica { get; set; }
        public Nullable<int> IDPosiljkaNarudzba { get; set; }
        public Nullable<int> IDBilje { get; set; }
    
        public virtual Bilje Bilje { get; set; }
        public virtual MjernaJedinica MjernaJedinica { get; set; }
        public virtual PosiljkaNarudzba PosiljkaNarudzba { get; set; }
    }
}
