//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramskoInzenjerstvo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bilje> Biljes { get; set; }
        public virtual DbSet<BiljeKupovina> BiljeKupovinas { get; set; }
        public virtual DbSet<BiljeNarudzba> BiljeNarudzbas { get; set; }
        public virtual DbSet<BiljeUporaba> BiljeUporabas { get; set; }
        public virtual DbSet<BiljnaPutovnica> BiljnaPutovnicas { get; set; }
        public virtual DbSet<Kupac> Kupacs { get; set; }
        public virtual DbSet<MjernaJedinica> MjernaJedinicas { get; set; }
        public virtual DbSet<NarodnoIme> NarodnoImes { get; set; }
        public virtual DbSet<PosiljkaKupovina> PosiljkaKupovinas { get; set; }
        public virtual DbSet<PosiljkaNarudzba> PosiljkaNarudzbas { get; set; }
        public virtual DbSet<PosiljkaStanje> PosiljkaStanjes { get; set; }
        public virtual DbSet<Rasadnik> Rasadniks { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
