//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramskoInzenjerstvo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bilje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bilje()
        {
            this.BiljeKupovinas = new HashSet<BiljeKupovina>();
            this.BiljeNarudzbas = new HashSet<BiljeNarudzba>();
            this.BiljeUporabas = new HashSet<BiljeUporaba>();
            this.BiljnaPutovnicas = new HashSet<BiljnaPutovnica>();
            this.NarodnoImes = new HashSet<NarodnoIme>();
            this.Rasadniks = new HashSet<Rasadnik>();
        }
        [Display(Name = "ID biljke")]
        public int IDBilje { get; set; }
        [Required(ErrorMessage = "Cijena je obavezno polje")]

        public decimal Cijena { get; set; }
        [MaxLength(20, ErrorMessage = "Maksimalno 20 znakova")]
        [Required(ErrorMessage = "Rod je obavezno polje")]
        public string Rod { get; set; }
        [Required(ErrorMessage = "Vrsta je obavezno polje")]
        [MaxLength(20, ErrorMessage = "Maksimalno 20 znakova")]
        public string Vrsta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BiljeKupovina> BiljeKupovinas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BiljeNarudzba> BiljeNarudzbas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BiljeUporaba> BiljeUporabas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BiljnaPutovnica> BiljnaPutovnicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NarodnoIme> NarodnoImes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rasadnik> Rasadniks { get; set; }
    }
}
