//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramskoInzenjerstvo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BiljeKupovina
    {
        public int IDBiljeKupovina { get; set; }
        [Required(ErrorMessage = "Kolicina je obavezno polje")]
       
        public int Kolicina { get; set; }
       
        [Required(ErrorMessage = "Cijena je obavezno polje")]
        public decimal CijenaKupovno { get; set; }
        public Nullable<int> IDMjernaJedinica { get; set; }
        public Nullable<int> IDPosiljkaKupovina { get; set; }
        public Nullable<int> IDBilje { get; set; }
    
        public virtual Bilje Bilje { get; set; }
        public virtual MjernaJedinica MjernaJedinica { get; set; }
        public virtual PosiljkaKupovina PosiljkaKupovina { get; set; }
    }
}
