//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramskoInzenjerstvo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiljnaPutovnica
    {
        public int IDBiljnaPutovnica { get; set; }
        public string Naziv { get; set; }
        public string Drzava { get; set; }
        public string Podrijetlo { get; set; }
        public string Kod { get; set; }
        public Nullable<int> IDBilje { get; set; }
    
        public virtual Bilje Bilje { get; set; }
    }
}
