//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramskoInzenjerstvo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kupac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kupac()
        {
            this.PosiljkaKupovinas = new HashSet<PosiljkaKupovina>();
            this.PosiljkaNarudzbas = new HashSet<PosiljkaNarudzba>();
        }
    
        public int IDKupac { get; set; }
        [MaxLength(30, ErrorMessage = "Maksimalno 30 znakova")]
        [Required(ErrorMessage = "Ime je obavezno polje")]
        public string Ime { get; set; }
        [Required(ErrorMessage = "Prezime je obavezno polje")]
        public string Prezime { get; set; }
        [Required(ErrorMessage = "Broj telefona je obavezno polje")]
        [RegularExpression("[^0-9]", ErrorMessage = "Samo brojevi")]
        public string BrojTel { get; set; }
        [Required(ErrorMessage = "Email je obavezno polje")]
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PosiljkaKupovina> PosiljkaKupovinas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PosiljkaNarudzba> PosiljkaNarudzbas { get; set; }
    }
}
