//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramskoInzenjerstvo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosiljkaKupovina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PosiljkaKupovina()
        {
            this.BiljeKupovinas = new HashSet<BiljeKupovina>();
        }
    
        public int IDPosiljkaKupovina { get; set; }
        public System.DateTime Datum { get; set; }
        public Nullable<int> IDKupac { get; set; }
        public Nullable<int> IDPosiljkaStanje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BiljeKupovina> BiljeKupovinas { get; set; }
        public virtual Kupac Kupac { get; set; }
        public virtual PosiljkaStanje PosiljkaStanje { get; set; }
    }
}
