//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramskoInzenjerstvo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Rasadnik
    {
        public int IDRasadnik { get; set; }
        [MaxLength(20, ErrorMessage = "Maksimalno 20 znakova")]
        [Required(ErrorMessage = "Vrsta je obavezno polje")]
        public string Vrsta { get; set; }
        [MaxLength(20, ErrorMessage = "Maksimalno 20 znakova")]
        [Required(ErrorMessage = "Lokacija je obavezno polje")]
        public string Lokacija { get; set; }
        public Nullable<int> IDBilje { get; set; }
    
        public virtual Bilje Bilje { get; set; }
    }
}
